name: Build and deploy Next.js (standalone) to Azure Web App

on:
  push:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "public/**"
      - "package.json"
      - "package-lock.json"
      - "next.config.js"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

concurrency:
  group: pos-frontend-azure-deploy
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build (Next.js standalone)
        run: npm run build

      - name: Assemble deploy folder
        run: |
          rm -rf deploy
          mkdir -p deploy/.next
          # standalone 本体
          cp -r .next/standalone/* deploy/
          # static / public
          cp -r .next/static deploy/.next/static
          if [ -d "public" ]; then cp -r public deploy/public; fi
          # ★ 重要：App Service の起動用に package.json も同梱（"start": "node server.js" を想定）
          cp package.json deploy/

      - name: Zip package
        run: |
          cd deploy
          zip -r ../app.zip .
          cd ..

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v4    # ← v4 に更新
        with:
          app-name: app-002-gen10-step3-1-node-oshima6
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: app.zip
          clean: true                     # ← これがポイント
